### ISSUE TITLE
HTTP/1.1 502 Bad Gateway Error Due to Default Lambda-Proxy

### ISSUE THREAD

**Issue by ezzye** [jethrocarr/serverless-java-example#1]
Need to add `integration: lambda` to `serverless.yml` to prevent serverless from defaulting to lambda-proxy.

As lambda-proxy needs a specific response see `Output Format of a Lambda Function for Proxy Integration` at bottom of page http://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-set-up-simple-proxy.html

For Example:
```
events:
     - http:
         path: hello
         integration: lambda
         method: get
         response:
           headers:
             Content-Type: "'text/html'"
           template: $input.path('$')
```

I think you need to update the example.
